import { TempleEvent } from '../../../shared/models/event.model';

/**
 * Demo events — used while Sanity isn't configured. Spread across many months
 * + types so the calendar widget and chip filters have meaningful data to show.
 *
 * Replace by configuring a real Sanity project; the effect will switch over
 * automatically based on SanityService.isConfigured.
 */
export const DEMO_EVENTS: TempleEvent[] = [
  // ---- Upcoming (relative to ~mid-2026) ----
  {
    _id: 'demo-e-01', _type: 'event', kind: 'sinh-hoat',
    title: 'Lớp giáo lý cuối tuần',
    slug: { current: 'lop-giao-ly-cuoi-tuan-2-5' },
    excerpt: 'Lớp Phật pháp căn bản dành cho Phật tử mới phát tâm.',
    startsAt: '2026-05-02T08:30:00+07:00',
    location: 'Nhà hậu',
    recurring: true,
  },
  {
    _id: 'demo-e-02', _type: 'event', kind: 'phong-sinh',
    title: 'Phóng sinh đầu tháng',
    slug: { current: 'phong-sinh-dau-thang-5' },
    excerpt: 'Mời Phật tử cùng phát tâm phóng sinh, hồi hướng pháp giới chúng sinh.',
    startsAt: '2026-05-03T07:00:00+07:00',
    lunarDate: 'Mùng 1 tháng 4 ÂL',
    location: 'Hồ sen',
    recurring: true,
  },
  {
    _id: 'demo-e-03', _type: 'event', kind: 'sinh-hoat',
    title: 'Lớp Phật Pháp căn bản (mở lớp mới)',
    slug: { current: 'lop-phat-phap-can-ban' },
    excerpt: 'Khoá học 12 buổi — từ Tứ Diệu Đế đến Bát Chánh Đạo.',
    startsAt: '2026-05-10T09:00:00+07:00',
    location: 'Phòng học',
  },
  {
    _id: 'demo-e-04', _type: 'event', kind: 'le-via',
    title: 'Đại lễ Phật Đản — PL.2569',
    slug: { current: 'phat-dan-2569' },
    excerpt: 'Nghi lễ tắm Phật, thuyết pháp, dâng hoa cúng dường tại chánh điện.',
    startsAt: '2026-05-14T06:00:00+07:00',
    lunarDate: 'Rằm tháng Tư âm lịch',
    location: 'Đại hùng bảo điện',
    recurring: true,
  },
  {
    _id: 'demo-e-05', _type: 'event', kind: 'sinh-hoat',
    title: 'Tụng kinh Pháp Hoa cuối tháng',
    slug: { current: 'tung-kinh-phap-hoa-5' },
    excerpt: 'Tụng kinh Diệu Pháp Liên Hoa — tụng từng phẩm.',
    startsAt: '2026-05-31T19:30:00+07:00',
    location: 'Chánh điện',
    recurring: true,
  },
  {
    _id: 'demo-e-06', _type: 'event', kind: 'khoa-tu',
    title: 'Khoá tu một ngày an lạc',
    slug: { current: 'khoa-tu-mot-ngay-thang-6' },
    excerpt: 'Hành thiền, nghe pháp thoại, chia sẻ kinh nghiệm tu tập.',
    startsAt: '2026-06-02T07:30:00+07:00',
    location: 'Sân thiền',
    recurring: true,
  },
  {
    _id: 'demo-e-07', _type: 'event', kind: 'sinh-hoat',
    title: 'Đêm thiền trà',
    slug: { current: 'dem-thien-tra-thang-6' },
    excerpt: 'Cùng tịnh tâm bên ấm trà, đối thoại nhẹ nhàng về tu tập.',
    startsAt: '2026-06-28T20:00:00+07:00',
    location: 'Sân vườn',
  },
  {
    _id: 'demo-e-08', _type: 'event', kind: 'khoa-tu',
    title: 'Khoá tu một ngày an lạc',
    slug: { current: 'khoa-tu-mot-ngay-thang-7' },
    excerpt: 'Tiếp nối khoá tu định kỳ hàng tháng.',
    startsAt: '2026-07-07T07:30:00+07:00',
    location: 'Sân thiền',
    recurring: true,
  },
  {
    _id: 'demo-e-09', _type: 'event', kind: 'le-via',
    title: 'Vía Bồ Tát Quán Thế Âm',
    slug: { current: 'via-quan-am-19-6' },
    excerpt: 'Đại chúng đồng niệm danh hiệu Đức Quán Thế Âm Bồ Tát.',
    startsAt: '2026-07-19T07:00:00+07:00',
    lunarDate: '19 tháng 6 âm lịch',
    location: 'Chánh điện',
    recurring: true,
  },
  {
    _id: 'demo-e-10', _type: 'event', kind: 'phong-sinh',
    title: 'Phóng sinh nhân dịp Vu Lan',
    slug: { current: 'phong-sinh-vu-lan' },
    excerpt: 'Hồi hướng công đức cho cha mẹ hiện tiền và nhiều đời nhiều kiếp.',
    startsAt: '2026-08-16T15:00:00+07:00',
    location: 'Sông',
  },
  {
    _id: 'demo-e-11', _type: 'event', kind: 'le-via',
    title: 'Đại lễ Vu Lan báo hiếu',
    slug: { current: 'vu-lan-2026' },
    excerpt: 'Tụng kinh Vu Lan — Báo Hiếu, lễ cài hoa hồng tưởng nhớ song thân.',
    startsAt: '2026-08-17T06:00:00+07:00',
    lunarDate: 'Rằm tháng Bảy âm lịch',
    location: 'Đại hùng bảo điện',
    recurring: true,
  },
  {
    _id: 'demo-e-12', _type: 'event', kind: 'khoa-tu',
    title: 'Khoá tu thanh niên Phật tử',
    slug: { current: 'khoa-tu-thanh-nien-2026' },
    excerpt: 'Khoá tu cuối tuần dành riêng cho Phật tử trẻ.',
    startsAt: '2026-09-12T07:00:00+07:00',
    endsAt: '2026-09-13T17:00:00+07:00',
    location: 'Sân thiền',
  },
  {
    _id: 'demo-e-13', _type: 'event', kind: 'le-via',
    title: 'Vía Bồ Tát Quán Thế Âm xuất gia',
    slug: { current: 'via-quan-am-19-9' },
    excerpt: 'Pháp hội tưởng niệm ngày Bồ Tát phát tâm xuất gia.',
    startsAt: '2026-10-22T07:00:00+07:00',
    lunarDate: '19 tháng 9 âm lịch',
    location: 'Chánh điện',
    recurring: true,
  },
  {
    _id: 'demo-e-14', _type: 'event', kind: 'le-via',
    title: 'Vía Đức Phật A Di Đà',
    slug: { current: 'via-a-di-da' },
    excerpt: 'Tụng Kinh A Di Đà, niệm danh hiệu nguyện sinh Tây Phương Cực Lạc.',
    startsAt: '2026-12-06T07:00:00+07:00',
    lunarDate: '17 tháng 11 âm lịch',
    location: 'Chánh điện',
    recurring: true,
  },

  // ---- Past ----
  {
    _id: 'demo-e-15', _type: 'event', kind: 'le-via',
    title: 'Đại lễ Phật Đản — PL.2569',
    slug: { current: 'phat-dan-2025' },
    excerpt: 'Đại lễ tắm Phật năm 2025.',
    startsAt: '2025-05-22T06:00:00+07:00',
    lunarDate: 'Rằm tháng Tư âm lịch 2025',
    location: 'Đại hùng bảo điện',
  },
  {
    _id: 'demo-e-16', _type: 'event', kind: 'le-via',
    title: 'Đại lễ Vu Lan báo hiếu — 2025',
    slug: { current: 'vu-lan-2025' },
    excerpt: 'Lễ Vu Lan năm 2025.',
    startsAt: '2025-08-28T06:00:00+07:00',
    lunarDate: 'Rằm tháng Bảy âm lịch 2025',
    location: 'Đại hùng bảo điện',
  },
  {
    _id: 'demo-e-17', _type: 'event', kind: 'khoa-tu',
    title: 'Khoá tu thiếu nhi mùa hè',
    slug: { current: 'khoa-tu-thieu-nhi-2024' },
    excerpt: 'Khoá tu hè dành cho thiếu nhi 8-15 tuổi.',
    startsAt: '2024-06-15T07:00:00+07:00',
    location: 'Sân thiền',
  },
];
